import turtle
turtle.bgcolor("#B80F55")
turtle.title("Pattern")
hexa= turtle.Turtle()
rexa=hexa.clone()
nexa=hexa.clone()
mexa=hexa.clone()
hexa.fillcolor("#1281B8")
rexa.fillcolor("#2EB85E")
nexa.fillcolor("#F57900")
mexa.fillcolor("#F59BE2")
hexa.begin_fill()
rexa.begin_fill()
nexa.begin_fill()
mexa.begin_fill()
for i in range (6):
    hexa.forward(200)
    hexa.right(300)
    rexa.forward(200)
    rexa.left(300)
    nexa.left(300)
    nexa.forward(200)
    mexa.right(300)
    mexa.forward(200)
hexa.end_fill()
rexa.end_fill()
nexa.end_fill()
mexa.end_fill()
turtle.done()
